CREATE TABLE "users" (
  "id" VARCHAR(255) PRIMARY KEY NOT NULL,
  "email" VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
